### ISSUE TITLE
Social Media Links are not set up.

### ISSUE THREAD

**Issue by rohailtaha** [MainakRepositor/Naveen#1]
Hello, your portfolio design is inspirational. 
I have noticed that the links to your social media profiles present in the **home** page and **contact** page are linking to your same portfolio.
I wonder if you are yet to update it or it is a mistake.

**Comment by MainakRepositor** [comment]
@rohailtaha Hello buddy!! Thanks for reaching out. I am glad that you liked the template. Actually I had made this for a client last year and for some reasons he wanted a change of the design. So, I kept this as a standby. Yeah, since I hadn't assigned the links, so they all will be pointing to the homepage.
